#!/usr/bin/env perl

use Dancer;
use Dancer::Plugin::DBIC;

get '/profile/:id' => sub {
    my $user = foo->resultset('Users')->find(params->{id});
    template user_profile => { user => $user };
};

dance;

# Dancer Configuration File

plugins:
  DBIC:
    foo:
      dsn:  "dbi:mysql:db_foo"
      user: "root"
      pass: "****"
      options:
        RaiseError: 1
        PrintError: 1
